<?php
$phrase['Project statistics'] = getphrase("Project statistics");
$phrase['Trade History Based on Project Signals'] = getphrase("Trade History Based on Project Signals");
$phrase['Statistics of purchase and sale transactions'] = getphrase("Statistics of purchase and sale transactions");
$phrase['Demo portfolio notice'] = getphrase("Simulation of portfolio performance based on real trading activity and signals generated by the system since its launch. The initial capital ($10,000) is hypothetical and used for illustrative modeling.");
$phrase['Demo label'] = getphrase("Demo");
/* === Добавлено: фразы для таблиц === */
$phrase['Total number of operations (buy/sell)'] = getphrase("Total number of operations (buy/sell)");
$phrase['Period from'] = getphrase("Period from");
$phrase['Deal share of capital'] = getphrase("Deal share of capital");
$phrase['Maximum exposure'] = getphrase("Maximum exposure");
$phrase['Average exposure'] = getphrase("Average exposure");
$phrase['Total profit'] = getphrase("Total profit");
$phrase['Average profit per trade'] = getphrase("Average profit per trade");
$phrase['Final capital'] = getphrase("Final capital");
$phrase['Annual return (CAGR)'] = getphrase("Annual return (CAGR)");
$phrase['Profit for the last 30 days'] = getphrase("Profit for the last 30 days");
$phrase['Trade history'] = getphrase("Trade history");
$phrase['Type'] = getphrase("Type");
$phrase['Asset'] = getphrase("Asset");
$phrase['Deal Time'] = getphrase("Deal Time");
$phrase['before deal ($)'] = getphrase("before deal")." ($)";
$phrase['Deal amount ($)'] = getphrase("Deal amount ($)");
$phrase['Profit ($)'] = getphrase("Profit")." ($)";
$phrase['Profit (%)'] = getphrase("Profit")." (%)";
$phrase['Free capital'] = getphrase("Free capital");
$phrase['after deal ($)'] = getphrase("after deal")." ($)";
$phrase['Portfolio size ($)'] = getphrase("Portfolio size")." ($)";
$phrase['Sold'] = getphrase("Sold");
$phrase['Not yet sold'] = getphrase("Not yet sold");
$phrase['Bought'] = getphrase("Bought");
$phrase['No deals for the selected period.'] = getphrase("No deals for the selected period.");

$blog_name = $phrase['Project statistics'];
$blog_description = $phrase['Statistics of purchase and sale transactions   '];
$blogsidebar = get_template("blogsidebar");
$blog_css = get_template("blog-css");

$page_content_html = "";

include_once(ROOTDIR . "projects/" . $config['project_path'] . "/engine/cleanpage.class.php");

$final_html = get_template("clean_page.twig");

$data_objects['page']['type'] = 'website';
$data_objects['page']['app'] = true;

// **************************************** ЛОГИКА:

if (isset($_GET['period'])) $_POST['period'] = $_GET['period'];

if ($_POST['period'] == '1y' || empty($_POST['period'])) {
    $dateto = date('Y-m-d', strtotime('+1 day'));
    $datefrom = date('Y-m-d', strtotime('-1 year'));
    if ($datefrom < '2025-10-04') $datefrom = '2025-10-04';
}

if ($_POST['period'] == '1m') {
    $dateto = date('Y-m-d', strtotime('+1 day'));
    $datefrom = date('Y-m-d', strtotime('-1 month'));
}

$deals = $db->super_query("
SELECT c1.curr,
       c1.timebuy AS buytime,
       c1.timesale AS saletime,
       ROUND(c1.profit / (c1.sumbuy / 100), 2) AS profitperc,
       c1.sold
FROM cryptotrade c1
JOIN (
  SELECT curr,
         FLOOR(UNIX_TIMESTAMP(timebuy) / (10 * 60)) AS tgroup,
         MIN(uid) AS keep_uid
  FROM cryptotrade
  GROUP BY curr, tgroup
) g
  ON g.curr = c1.curr
 AND g.keep_uid = c1.uid
 AND FLOOR(UNIX_TIMESTAMP(c1.timebuy) / (10 * 60)) = g.tgroup
WHERE (c1.profit > 0 OR c1.timesale > '2025-09-01' OR c1.sold = 0)
  AND (
    (c1.sold = 1 AND c1.timesale BETWEEN '$datefrom' AND '$dateto')
     OR (c1.timebuy BETWEEN '$datefrom' AND '$dateto')
  )
UNION
SELECT curr, lasttimebuy as buytime, timesell as saletime, round(profit/(pricebuy/100),2) as profitperc, sold
FROM cryptosignals_trade
WHERE (profit>0 or sold=0)
  and ((sold=1 and (timesell >= '$datefrom' and timesell <= '$dateto'))
  or (lasttimebuy >= '$datefrom' and lasttimebuy <= '$dateto'))
  and curr not in (select curr from cryptotrade where date(timebuy)=date(cryptosignals_trade.lasttimebuy) or (date(timesale)=date(cryptosignals_trade.timesell) and cryptosignals_trade.sold=1 and cryptotrade.sold=1))
", true);

// ------------------------------
// НАСТРОЙКИ
// ------------------------------
$initial_capital = 10000.0;  // стартовый капитал
$deal_share      = 0.01;     // доля от свободного капитала
$max_exposure    = 0.90;     // ограничитель экспозиции

if (!empty($_GET['startcup']))     $initial_capital = $_GET['startcup'] + 1 - 1;
if (!empty($_GET['dealshare']))    $deal_share      = $_GET['dealshare']/100;
if (!empty($_GET['maxexposure']))  $max_exposure    = $_GET['maxexposure']/100;

// ------------------------------
// ФУНКЦИЯ: закрыть сделку и записать лог (SELL)
// ------------------------------
function close_and_log($pos, &$current_capital, &$deal_log, &$active) {
    $capital_before = $current_capital;

    $proceeds = $pos['amount'] * $pos['factor'];
    $profit_amount = $pos['amount'] * ($pos['factor'] - 1.0);
    $current_capital += $proceeds;

    if (!empty($active) && is_array($active)) {
        foreach ($active as $k => $x) {
            if (
                isset($x['curr'], $x['buytime'], $x['saletime']) &&
                $x['curr'] === $pos['curr'] &&
                abs($x['buytime'] - $pos['buytime']) < 2 &&
                abs($x['saletime'] - $pos['saletime']) < 2
            ) {
                unset($active[$k]);
                break;
            }
        }
    }

    $in_market_after = 0.0;
    if (!empty($active) && is_array($active)) {
        foreach ($active as $x) {
            if (isset($x['amount'])) {
                $in_market_after += (float)$x['amount'];
            }
        }
    }

    $portfolio_size = $current_capital + $in_market_after;

    $deal_log[] = array(
        'type'                 => 'SELL',
        'curr'                 => $pos['curr'],
        'dealtime'             => date('Y-m-d H:i:s', $pos['saletime']),
        'relatedtime'          => date('Y-m-d H:i:s', $pos['buytime']),
        'capital_before_deal'  => $capital_before,
        'invest'               => $proceeds,
        'profit_amount'        => $profit_amount,
        'profitperc'           => $pos['profitperc'],
        'capital_after_deal'   => $current_capital,
        'portfolio_size'       => $portfolio_size
    );
}

// ------------------------------
// ЕСЛИ СДЕЛОК НЕТ
// ------------------------------
$middle_profitperc = 0.0;
$noDeals = (!is_array($deals) || count($deals) === 0);
if ($noDeals) {
    $report = array(
        'count'         => 0,
        'period_from'   => $datefrom,
        'period_to'     => $dateto,
        'deal_share'    => $deal_share * 100,
        'max_exposure'  => $max_exposure * 100,
        'avg_exposure'  => 0.0,
        'total_profit'  => 0.0,
        'final_capital' => $initial_capital,
        'cagr'          => 0.0,
    );
    $deal_log = array();
} else {

    foreach ($deals as &$d) {
        $d['buytime']    = strtotime($d['buytime']);
        $d['saletime']   = !empty($d['saletime']) ? strtotime($d['saletime']) : null;
        $d['profitperc'] = (float)$d['profitperc'];
        $d['sold']       = isset($d['sold']) ? (int)$d['sold'] : 0;
    }
    unset($d);

    usort($deals, function($a, $b) {
        if ($a['buytime'] == $b['buytime']) return 0;
        return ($a['buytime'] < $b['buytime']) ? -1 : 1;
    });

    $current_capital = $initial_capital;
    $active = array();
    $deal_log = array();
    $exposure_log = array();

    $total_profitperc = 0;
    foreach ($deals as $deal) {
        $buy    = $deal['buytime'];
        $sell   = $deal['saletime'];
        $profitperc = $deal['profitperc'];
        $total_profitperc += $profitperc;
        $factor = 1.0 + ($profitperc / 100.0);

        $new_active = array();
        foreach ($active as $a) {
            if ($a['sold'] == 1 && !empty($a['saletime']) && $a['saletime'] <= $buy) {
                close_and_log($a, $current_capital, $deal_log, $active);
            } else {
                $new_active[] = $a;
            }
        }
        $active = $new_active;

        $capital_before = $current_capital;
        $invest = $current_capital * $max_exposure * $deal_share;
        if ($invest <= 0) continue;

        $current_capital -= $invest;
        $active[] = array(
            'curr'            => $deal['curr'],
            'buytime'         => $buy,
            'saletime'        => $sell,
            'sold'            => $deal['sold'],
            'amount'          => $invest,
            'factor'          => $factor,
            'profitperc'      => $profitperc,
            'capital_before'  => $capital_before
        );

        $portfolio_size = $current_capital;
        foreach ($active as $a) $portfolio_size += $a['amount'];

        $deal_log[] = array(
            'type'                 => 'BUY',
            'curr'                 => $deal['curr'],
            'dealtime'             => date('Y-m-d H:i:s', $buy),
            'relatedtime'          => date('Y-m-d H:i:s', $sell),
            'capital_before_deal'  => $capital_before,
            'invest'               => $invest,
            'profit_amount'        => 0.0,
            'profitperc'           => $profitperc,
            'capital_after_deal'   => $current_capital,
            'portfolio_size'       => $portfolio_size
        );

        $in_market = 0.0;
        foreach ($active as $a) $in_market += $a['amount'];
        $den = $current_capital + $in_market;
        $exposure_log[] = ($den > 0) ? ($in_market / $den) : 0.0;
    }

    $middle_profitperc = round($total_profitperc / count($deals), 2);

    if (!empty($active)) {
        usort($active, function($x, $y) {
            return ($x['saletime'] ?? PHP_INT_MAX) <=> ($y['saletime'] ?? PHP_INT_MAX);
        });
        $still_open = array();
        foreach ($active as $a) {
            if ($a['sold'] == 1 && !empty($a['saletime'])) {
                close_and_log($a, $current_capital, $deal_log, $active);
            } else {
                $still_open[] = $a;
            }
        }
        $active = $still_open;
    }

    $final_portfolio_value = $current_capital;

    $now = 0;
    if (!empty($deal_log)) {
        $last_log = end($deal_log);
        $now = strtotime($last_log['dealtime']);
    }
    $active_open = array_filter($active, function($x) use ($now) {
        return $x['saletime'] > $now;
    });

    $in_market_now = 0.0;
    foreach ($active_open as $a) {
        $in_market_now += $a['amount'];
    }
    $final_portfolio_value += $in_market_now;

    if (!empty($deal_log)) {
        $last_log = end($deal_log);
        if (isset($last_log['portfolio_size']) && $last_log['portfolio_size'] > $final_portfolio_value) {
            $final_portfolio_value = $last_log['portfolio_size'];
        }
    }

    $active = array();

    $final_capital = $final_portfolio_value;

    $in_market_now = 0.0;
    foreach ($active as $a) $in_market_now += $a['amount'];
    $final_portfolio_value += $in_market_now;

    $final_capital = $final_portfolio_value;
    $start_time = min(array_column($deals, 'buytime'));
    $end_time   = max(array_column($deals, 'saletime'));
    $total_profit = (($final_capital - $initial_capital) / $initial_capital) * 100.0;
    $period_sec  = max($end_time - $start_time, 1);
    $period_days = $period_sec / 86400.0;
    $cagr = ($period_days < 30) ? null : pow($final_capital / $initial_capital, 365.25 / $period_days) - 1.0;
    $avg_exposure = count($exposure_log) ? array_sum($exposure_log) / count($exposure_log) : 0.0;

    $report = array(
        'count'         => count($deal_log),
        'period_from'   => date('Y-m-d H:i:s', $start_time),
        'period_to'     => date('Y-m-d H:i:s', $end_time),
        'deal_share'    => $deal_share * 100,
        'max_exposure'  => $max_exposure * 100,
        'avg_exposure'  => $avg_exposure * 100,
        'total_profit'  => $total_profit,
        'final_capital' => $final_portfolio_value,
        'cagr'          => $cagr,
    );
    // ------------------------------
    // ДОХОД ЗА ПОСЛЕДНИЕ 30 ДНЕЙ
    // ------------------------------
    $thirty_days_ago = strtotime('-30 days');
    $profit_last_30_days = 0.0;
    $capital_30_days_ago = $initial_capital;

    if (!empty($deal_log)) {
        // Находим капитал 30 дней назад
        foreach ($deal_log as $log) {
            $log_time = strtotime($log['dealtime']);
            if ($log_time <= $thirty_days_ago) {
                $capital_30_days_ago = $log['portfolio_size'];
            } else {
                break;
            }
        }

        // Текущий капитал — из последнего лога
        $last_log = end($deal_log);
        $current_capital_now = isset($last_log['portfolio_size']) ? $last_log['portfolio_size'] : $capital_30_days_ago;

        if ($capital_30_days_ago > 0) {
            $profit_last_30_days = (($current_capital_now - $capital_30_days_ago) / $capital_30_days_ago) * 100.0;
        }
    }

    $report['profit_last_30_days'] = $profit_last_30_days;
}

// ------------------------------
// ГРАФИЧЕСКИЙ JSON
// ------------------------------
$chartarray['dealscount']   = $report['count'];
$chartarray['total_profit'] = $report['total_profit'];
$chartarray['middle_profit']= $middle_profitperc;
if ($report['cagr'] === null)           $chartarray['cagr'] = $chartarray['total_profit'] * 12;
elseif ($_POST['period'] == '1y')       $chartarray['cagr'] = $report['total_profit'];
else                                    $chartarray['cagr'] = $report['cagr'] * 100;
$chartarray['middle_profit'] = $middle_profitperc;

// ------------------------------
// ПОДГОТОВКА ОТФОРМАТИРОВАННЫХ ЗНАЧЕНИЙ ДЛЯ HEREDOC
// ------------------------------
$f_count           = $report['count'];
$f_period          = $report['period_from'];
$f_deal_share      = number_format($report['deal_share'], 2) . " %";
$f_max_exposure    = number_format($report['max_exposure'], 2) . " %";
$f_avg_exposure    = number_format($report['avg_exposure'], 2) . " %";
$f_total_profit    = number_format($report['total_profit'], 2) . " %";
$f_profit_last_30_days = number_format($report['profit_last_30_days'], 2) . " %";
$f_middle_profit   = number_format($middle_profitperc, 2) . " %";
$f_final_capital   = "$" . number_format($report['final_capital'], 2);
$f_cagr            = ($report['cagr'] === null) ? 'N/A' : (number_format($report['cagr'] * 100, 2) . ' %');

// ------------------------------
// HTML + СТИЛИ
// ------------------------------
$page_content_html = <<<HTML
<style>
.crypto-report {
  font-family: 'Inter', sans-serif;
  color: #e0e0f0;
  border-radius: 12px;
  padding: 24px;
}
.crypto-title {
  color: #00e5ff;
  text-shadow: 0 0 10px rgba(0,255,255,0.5);
  font-size: 1.4rem;
  margin-bottom: 12px;
}
.crypto-subtitle {
  color: #8f93b7;
  margin-top: 24px;
  font-size: 1.1rem;
}

/* === Таблица сводной статистики === */
.crypto-summary {
  border-collapse: collapse;
  width: 100%;
  margin-top: 16px;
  background: rgba(20,22,35,0.6);
  box-shadow: 0 0 16px rgba(0,255,255,0.1);
  border: 1px solid rgba(0,255,255,0.2);
  border-radius: 12px;
  overflow: hidden;
}
.crypto-summary th, .crypto-summary td {
  padding: 10px 16px;
  text-align: right;
  border-bottom: 1px solid rgba(255,255,255,0.08);
}
.crypto-summary .left {
  text-align: left;
  color: #b0b3d6;
}
.crypto-summary tr:last-child td {
  border-bottom: none;
}
.crypto-summary tr:hover {
  background: rgba(0,255,255,0.04);
}
.crypto-summary td:last-child {
  color: #fff;
  font-weight: 600;
}
.crypto-summary tr:nth-last-child(-n+3) td {
  background: linear-gradient(90deg, rgba(0,255,255,0.05), rgba(77,255,184,0.05));
  font-weight: bold;
}

/* === Таблица сделок === */
.crypto-table {
  min-width: 900px;
  border-collapse: separate;   /* важно: separate, иначе sticky ломается */
  border-spacing: 0;
  width: 100%;
  background: rgba(15,17,25,0.6);
  border-radius: 12px;
  overflow: hidden;
  border: 1px solid rgba(255,255,255,0.05);
}
.crypto-table th, .crypto-table td {
  padding: 8px 12px;
  text-align: right;
  border-bottom: 1px solid rgba(255,255,255,0.05);
  color: #e0e0f0;
  font-size: 0.95rem;
}
.crypto-table th {
  text-align: center;
  color: #9ca3c9;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  font-size: 12px;
}

/* === Sticky шапка таблицы (залипание при scrollY > top-200) === */
.crypto-table thead {
  display: table-header-group;
  position: static;
}

/* когда активен is-sticky */
.crypto-table-wrapper.is-sticky thead {
  position: fixed;            /* фиксируем к экрану */
  top: 200px;
  left: 0;
  right: 0;
  z-index: 30;
  background: rgba(20, 22, 35, 0.9);
  backdrop-filter: blur(6px);
  box-shadow: 0 2px 8px rgba(0,255,255,0.08);
}
.crypto-table-wrapper.is-sticky thead th {
  background: rgba(20, 22, 35, 0.9);
}

/* === Контейнер таблицы === */
.crypto-table-wrapper {
  position: relative;
  width: 100%;
  overflow-x: auto; /* горизонтальный скролл */
  overflow-y: visible;
  -webkit-overflow-scrolling: touch;
  padding: 0;
  margin: 0;
}

/* === BUY / SELL строки === */
.crypto-table tr.buy td {
  color: inherit;
  background: none;
  box-shadow: none;
}

.crypto-table tr.sell td {
  color: #4dffb8;
  background: rgba(77,255,184,0.03);
  box-shadow: inset 0 0 6px rgba(77,255,184,0.08);
}
.crypto-table tr.negative td {
  color: #ff4d6d;
  background: rgba(255, 77, 109, 0.06);
  box-shadow: inset 0 0 8px rgba(255, 77, 109, 0.12);
}
.crypto-table tr.negative:hover td {
  background: rgba(255, 77, 109, 0.12);
  transition: background 0.2s ease;
}
.crypto-table tr:hover td {
  background: rgba(255,255,255,0.05);
  transition: background 0.2s ease;
}
/* === Текст мелкий === */
.crypto-small {
  color: #666a8a;
  font-size: 12px;
}

/* === Адаптив === */
@media (max-width: 900px) {
  .crypto-table, .crypto-summary {
    font-size: 12px;
  }
  .crypto-table th, .crypto-table td {
    padding: 6px 8px;
  }
}
/* Клон заголовка таблицы */
.crypto-table.fixed-header {
  border-collapse: separate;
  border-spacing: 0;
  background: rgba(20,22,35,0.95);
}

.crypto-table.fixed-header th {
  background: rgba(20,22,35,0.95);
}

.crypto-note {
  font-size: 0.9rem;
  color: #9ca3c9;
  margin-top: 4px;
  margin-bottom: 12px;
  line-height: 1.4;
  opacity: 0.8;
}
.crypto-note b {
  color: #00e5ff;
}
.crypto-label-demo {
  font-size: 0.7rem;
  text-transform: uppercase;
  background: rgba(0, 255, 255, 0.1);
  color: #00e5ff;
  padding: 2px 6px;
  border-radius: 4px;
  margin-left: 6px;
  font-weight: 600;
  letter-spacing: 0.05em;
}

/* === Отступ для заголовка === */
.h1stat {
  margin-top: -50px;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const wrapper = document.querySelector('.crypto-table-wrapper');
  const table = wrapper?.querySelector('.crypto-table');
  if (!wrapper || !table) return;

  // создаем клон заголовка
  const clone = table.querySelector('thead').cloneNode(true);
  const fixedHeader = document.createElement('table');
  fixedHeader.className = table.className + ' fixed-header';
  fixedHeader.appendChild(clone);
  fixedHeader.style.display = 'none';
  fixedHeader.style.position = 'fixed';
  fixedHeader.style.top = '95px';
  fixedHeader.style.left = wrapper.getBoundingClientRect().left + 'px';
  fixedHeader.style.zIndex = '50';
  fixedHeader.style.background = 'rgba(20,22,35,0.95)';
  fixedHeader.style.backdropFilter = 'blur(8px)';
  fixedHeader.style.borderBottom = '1px solid rgba(0,255,255,0.2)';
  fixedHeader.style.boxShadow = '0 2px 8px rgba(0,255,255,0.15)';
  fixedHeader.style.pointerEvents = 'none'; // чтобы не перекрывал клики
  document.body.appendChild(fixedHeader);

  function syncWidths() {
    const ths = table.querySelectorAll('thead th');
    const cloneThs = fixedHeader.querySelectorAll('thead th');
    if (ths.length !== cloneThs.length) return;

    const rect = wrapper.getBoundingClientRect();
    fixedHeader.style.left = rect.left + 'px';
    fixedHeader.style.width = rect.width + 'px';

    ths.forEach((th, i) => {
      cloneThs[i].style.width = th.offsetWidth + 'px';
    });
  }

  function toggleHeader() {
    if (window.innerWidth < 1024) {
      fixedHeader.style.display = 'none';
      return;
    }
    const rect = table.getBoundingClientRect();
    const tableTop = rect.top + window.scrollY;
    const tableBottom = tableTop + table.offsetHeight;
    const scrollY = window.scrollY;

    if (scrollY > tableTop - 95 && scrollY < tableBottom - 400) {
      if (fixedHeader.style.display === 'none') {
        syncWidths();
        fixedHeader.style.display = 'table';
      }
    } else {
      fixedHeader.style.display = 'none';
    }
  }

  window.addEventListener('scroll', toggleHeader, { passive: true });
  window.addEventListener('resize', syncWidths);
});

  // === Конвертация времени сделок в локальную зону пользователя ===
function localizeDealTimes(offsetHours = 0) {
  const dateRegex = /\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/g;

  document.querySelectorAll('.crypto-table td, .crypto-summary td').forEach(td => {
    const html = td.innerHTML;
    const newHtml = html.replace(dateRegex, match => {
      // создаем объект даты из UTC + смещение
      const utcDate = new Date(new Date(match.replace(' ', 'T') + 'Z').getTime() + offsetHours * 3600 * 1000);
      return utcDate.toLocaleString(undefined, {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit'
      });
    });
    if (newHtml !== html) td.innerHTML = newHtml;
  });
}
// выполняем после загрузки страницы
document.addEventListener('DOMContentLoaded', () => {
  // нужное смещение (обычно 0 или -1)
  localizeDealTimes(-1);
});
</script>
        
<h1 class="h1stat">{$phrase['Project statistics']}</h1>

<table class="crypto-summary">
<tr><td class="left">{$phrase['Total number of operations (buy/sell)']}</td><td>{$f_count}</td></tr>
<tr><td class="left">{$phrase['Period from']}</td><td>{$f_period}</td></tr>
<tr><td class="left">{$phrase['Deal share of capital']}</td><td>{$f_deal_share}</td></tr>
<tr><td class="left">{$phrase['Maximum exposure']}</td><td>{$f_max_exposure}</td></tr>
<tr><td class="left">{$phrase['Average exposure']}</td><td>{$f_avg_exposure}</td></tr>
<tr><td class="left">{$phrase['Average profit per trade']}</td><td>{$f_middle_profit}</td></tr>
<tr><td class="left">{$phrase['Profit for the last 30 days']}</td><td>{$f_profit_last_30_days}</td></tr>
<tr><td class="left">{$phrase['Annual return (CAGR)']}</td><td>{$f_cagr}</td></tr>
</table>
        
</div> <!-- ЭТА ТАБЛИЦА (НИЖЕ) ШИРОКАЯ И ДОЛЖНА БЫТЬ В СВОЕМ КОНТЕЙНЕРЕ, А НЕ В ГЛОБАЛЬНОМ -->

<div class="crypto-report">

<h3 class="crypto-subtitle">
  <span class="crypto-label-demo">{$phrase['Trade History Based on Project Signals']}</span>
</h3>
<p class="crypto-note">
  *{$phrase['Demo portfolio notice']}
</p>
<div class="crypto-table-wrapper">
<table class="crypto-table">
<thead>
<tr>
  <th>#</th>
  <th>{$phrase['Type']}</th>
  <th>{$phrase['Asset']}</th>
  <th>{$phrase['Deal Time']}</th>
  <th>{$phrase['Free capital before deal ($)']}</th>
  <th>{$phrase['Deal amount ($)']}</th>
  <th>{$phrase['Profit ($)']}</th>
  <th>{$phrase['Profit (%)']}</th>
  <th>{$phrase['Free capital after deal ($)']}</th>
  <th>{$phrase['Portfolio size ($)']}</th>
</tr>
</thead>
<tbody>
HTML;

if (!empty($deal_log)) {
    foreach ($deal_log as $i => $log) {
        $row_class = (strtoupper($log['type']) == 'BUY') ? 'buy' : 'sell';
        if (isset($log['profit_amount']) && $log['profit_amount'] < 0) {
            $row_class = 'negative';
        }
        $related_label = "";
        if (strtoupper($log['type']) == 'SELL') {
            // для продажи показываем дату покупки
            $related_label = "<div class='crypto-small'>{$phrase['Bought']}: ".$log['relatedtime']."</div>";
        } elseif (strtoupper($log['type']) == 'BUY') {
            // если продажа была — показываем дату, иначе "Ещё не продано"
            if (!empty($log['relatedtime']) && $log['profitperc'] != 0) {
                $related_label = "<div class='crypto-small'>{$phrase['Sold']}: ".$log['relatedtime']."</div>";
            } else {
                $related_label = "<div class='crypto-small'>{$phrase['Not yet sold']}</div>";
            }
        }
        if (strtoupper($log['type']) == 'BUY') {
            $page_content_html .= "<tr class='".$row_class."'>"
              . "<td>".($i+1)."</td>"
              . "<td>".htmlspecialchars($log['type'])."</td>"
              . "<td>".htmlspecialchars($log['curr'])."</td>"
              . "<td>".htmlspecialchars($log['dealtime']).$related_label."</td>"
              . "<td>".number_format($log['capital_before_deal'], 2)."</td>"
              . "<td>".number_format($log['invest'], 2)."</td>"
              . "<td></td>"
              . "<td></td>"
              . "<td>".number_format($log['capital_after_deal'], 2)."</td>"
              . "<td>".number_format($log['portfolio_size'], 2)."</td>"
              . "</tr>";
        } else {
            $page_content_html .= "<tr class='".$row_class."'>"
              . "<td>".($i+1)."</td>"
              . "<td>".htmlspecialchars($log['type'])."</td>"
              . "<td>".htmlspecialchars($log['curr'])."</td>"
              . "<td>".htmlspecialchars($log['dealtime']).$related_label."</td>"
              . "<td>".number_format($log['capital_before_deal'], 2)."</td>"
              . "<td>".number_format($log['invest'], 2)."</td>"
              . "<td>".number_format($log['profit_amount'], 2)."</td>"
              . "<td>".number_format($log['profitperc'], 2)." %</td>"
              . "<td>".number_format($log['capital_after_deal'], 2)."</td>"
              . "<td>".number_format($log['portfolio_size'], 2)."</td>"
              . "</tr>";
        }
    }
} else {
    $page_content_html .= "<tr><td colspan='10' class='crypto-small'>{$phrase['No deals for the selected period.']}</td></tr>";
}
$page_content_html .= "</tbody></table></div></div>
<div class=\"e-container mt-half-max\"><!-- ОПЯТЬ ОТКРЫВАЕМ ГЛОБАЛЬНЫЙ КОНТЕЙНЕР -->";

if (!empty($report['count']))
{
    $project_stat['1y_dealscount'] = $report['count'];
    $project_stat['1m_total_profit'] = round($report['profit_last_30_days'],2);
    $project_stat['1y_middle_profit'] = $middle_profitperc;
    $project_stat['1y_cagr'] = $report['cagr'] * 100;
    $project_stat['1y_total_profit'] = round($project_stat['1y_cagr'],2);
    $project_stat['1y_middle_profit'] = $middle_profitperc;

    memcache_set($memcache_obj, "projecttradestat".$thisprojectid, $project_stat, 0, 86400);
}
// в кроне обязательно shell_exec("curl -A 'Cron' -m 1 -s 'https://cryptoapi.ai/en/alldeals' > /dev/null 2>/dev/null &");

// ******************************* КОНЕЦ ЛОГИКИ (HTML)

$tpl = [
  '{$page_content_html}' => $page_content_html,
];

$final_html = strtr($final_html, $tpl);